test:main.o scrolling.o
	gcc main.o scrolling.o -o test -lSDL -lSDL_image -lSDL_mixer -g
main.o:main.c
	gcc -c main.c -lSDL -lSDL_image -lSDL_mixer -g
scrolling.o:scrolling.c
	gcc -c scrolling.c -lSDL -lSDL_image -lSDL_mixer -g


