prog:scrolling.o collision.o perso.o map.o ennemi.o level1.o jeux.o main.o menuingame.o enigme.o
	gcc scrolling.o collision.o perso.o map.o ennemi.o  level1.o jeux.o main.o menuingame.o enigme.o -lSDL -lSDL_image -lSDL_mixer -o prog -g

main.o:main.c
	gcc -c main.c -g

jeux.o:jeux.c
	gcc -c jeux.c -g

enigme.o:enigme.c
	gcc -c enigme.c -g

level1.o:level1.c
	gcc -c level1.c -g


ennemi.o:ennemi.c
	gcc -c ennemi.c -g

map.o:map.c
	gcc -c map.c -g

perso.o:perso.c
	gcc -c perso.c -g

collision.o:collision.c
	gcc -c collision.c -g

scrolling.o:scrolling.c
	gcc -c scrolling.c -g

menuingame.o:menuingame.c
	gcc -c menuingame.c -g
